services:  # コンポースするサービスたち
    mcmp-slave-srv:  # サービスの名前
        container_name: mcmp-slave  # コンテナ名
        build:  # ビルド設定
            context: ./mcmp-slave  # ビルドプロセスが実行されるパス。
            dockerfile: Dockerfile  # Dockerfileのパス。
            args:  # 引数
                - MULTIPAPER_SLAVE_URL=${MULTIPAPER_SLAVE_URL}
                - BASE_IMAGE=${BASE_IMAGE}
                - MAIN_IP=${MAIN_IP}
        volumes:  # ボリュームの保持
            - ./mcmp-slave/eula.txt:/root/mcmp-slave/eula.txt # eula
            - ./mcmp-slave/config:/root/mcmp-slave/config # setting file paper-global.yml
            - ./mcmp-slave/server.properties:/root/mcmp-slave/server.properties # setting file
            - ./mcmp-slave/spigot.yml:/root/mcmp-slave/spigot.yml # setting file
        ports:  # ホストマシンのポートとコンテナのポートをマッピングしてポートを公開
            - "25566:25565"  # masterが接続するポート
        restart: always  # コンテナの再起動
        environment:  # 環境変数
            EULA: "true"
            TZ: "Asia/Tokyo"
        tty: true  # コンテナ内で対話的操作を可能
